server.port=8085
spring.application.name=notification-service

# Base de datos
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/notificationdb}
spring.datasource.username=${DB_USER:jacobo}
spring.datasource.password=${DB_PASSWORD:jacobo123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:create-drop}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# RabbitMQ
spring.rabbitmq.addresses=${RABBITMQ_URL:amqps://znyracho:6OWkLPKTK6ayX4_Kc7ayjS2KeVROhj0d@moose.rmq.cloudamqp.com/znyracho}

# Exchange
rabbitmq.exchange=mindbridge.exchange

management.endpoints.web.exposure.include=health,info

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true